import React, { useState, useEffect, useMemo } from 'react';
import { Transaction, TransactionType } from '../types';
import { getTransactions, saveTransaction, deleteTransaction, updateTransaction, logoutUser } from '../services/storageService';
import { LogOut, Plus, Trash2, Home, Download, Loader2, ArrowUpDown, ArrowUp, ArrowDown, X, Edit, Save } from 'lucide-react';

interface DashboardProps {
  currentUser: string;
  onLogout: () => void;
}

type SortKey = 'date' | 'label' | 'amount';
type SortDirection = 'asc' | 'desc';

const Dashboard: React.FC<DashboardProps> = ({ currentUser, onLogout }) => {
  // Helper to get local date string YYYY-MM-DD
  const getLocalDate = () => {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    const day = String(today.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  // Helper to get local month string YYYY-MM
  const getLocalMonth = () => {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    return `${year}-${month}`;
  };

  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [amount, setAmount] = useState('');
  const [label, setLabel] = useState('');
  const [type, setType] = useState<TransactionType>(TransactionType.EXPENSE);
  const currentMonth = getLocalMonth();
  const [filterDate, setFilterDate] = useState(currentMonth); // YYYY-MM
  const [showForm, setShowForm] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  
  // Selection & Editing State
  const [selectedTransaction, setSelectedTransaction] = useState<Transaction | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);

  // Sorting State
  const [sortConfig, setSortConfig] = useState<{ key: SortKey; direction: SortDirection }>({
    key: 'date',
    direction: 'desc' // Default newest first
  });

  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentUser]);

  const loadData = async () => {
    setIsLoading(true);
    const data = await getTransactions();
    // Initial load
    setTransactions(data);
    setIsLoading(false);
  };

  const handleSaveTransaction = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!amount || !label) return;
    setIsSaving(true);

    if (editingId) {
      // Update existing
      const original = transactions.find(t => t.id === editingId);
      if (original) {
        const updatedPayload: Transaction = {
          ...original,
          amount: parseFloat(amount),
          label,
          type,
          // We keep the original date for now, or you could update it to today if desired
        };

        const success = await updateTransaction(updatedPayload);
        if (success) {
          setTransactions(prev => prev.map(t => t.id === editingId ? updatedPayload : t));
        }
      }
    } else {
      // Create new
      const newTransactionPayload: Transaction = {
        id: '', // ID is generated by Supabase
        amount: parseFloat(amount),
        label,
        date: getLocalDate(), 
        type,
      };

      const savedData = await saveTransaction(newTransactionPayload);
      if (savedData) {
        setTransactions(prev => [...prev, savedData]);
      }
    }
    
    setIsSaving(false);
    resetForm();
  };

  const resetForm = () => {
    setAmount('');
    setLabel('');
    setType(TransactionType.EXPENSE);
    setEditingId(null);
    setShowForm(false);
  };

  const handleRowClick = (t: Transaction) => {
    setSelectedTransaction(t);
  };

  const handleEditClick = () => {
    if (!selectedTransaction) return;
    setAmount(selectedTransaction.amount.toString());
    setLabel(selectedTransaction.label);
    setType(selectedTransaction.type);
    setEditingId(selectedTransaction.id);
    
    setShowForm(true);
    setSelectedTransaction(null); // Close modal
  };

  const handleDeleteClick = async () => {
    if (!selectedTransaction) return;
    if (window.confirm('ဖျက်ရန် သေချာပါသလား?')) {
      const success = await deleteTransaction(selectedTransaction.id);
      if (success) {
        setTransactions(prev => prev.filter(t => t.id !== selectedTransaction.id));
      }
    }
    setSelectedTransaction(null);
  };

  const handleLogout = async () => {
    await logoutUser();
    onLogout();
  }

  const handleExportCSV = () => {
    if (transactions.length === 0) return;
    
    // CSV Header
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Date,Label,Type,Amount\n";

    // CSV Rows
    transactions.forEach(t => {
      const row = `${t.date},${t.label},${t.type},${t.amount}`;
      csvContent += row + "\n";
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `money_tracker_${currentUser}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleSort = (key: SortKey) => {
    setSortConfig(current => {
      if (current.key === key) {
        return { key, direction: current.direction === 'asc' ? 'desc' : 'asc' };
      }
      return { key, direction: 'asc' };
    });
  };

  const getSortIcon = (columnKey: SortKey) => {
    if (sortConfig.key !== columnKey) return <ArrowUpDown size={14} className="ml-1 opacity-30 inline" />;
    return sortConfig.direction === 'asc' 
      ? <ArrowUp size={14} className="ml-1 text-primary inline" /> 
      : <ArrowDown size={14} className="ml-1 text-primary inline" />;
  };

  // Current Month Transactions + Sorting
  const filteredAndSortedTransactions = useMemo(() => {
    // 1. Filter by Month
    const filtered = transactions.filter(t => t.date.startsWith(filterDate));
    
    // 2. Sort
    return filtered.sort((a, b) => {
      let valA: string | number = a[sortConfig.key];
      let valB: string | number = b[sortConfig.key];

      if (sortConfig.key === 'label') {
        valA = a.label.toLowerCase();
        valB = b.label.toLowerCase();
      } else if (sortConfig.key === 'date') {
        // Use full timestamp if available for stable sort on same day
        if (valA === valB && a.created_at && b.created_at) {
             valA = a.created_at;
             valB = b.created_at;
        }
      }

      if (valA < valB) return sortConfig.direction === 'asc' ? -1 : 1;
      if (valA > valB) return sortConfig.direction === 'asc' ? 1 : -1;
      return 0;
    });
  }, [transactions, filterDate, sortConfig]);

  // Monthly Stats (For Income/Expense Cards)
  const monthlyStats = useMemo(() => {
    // Re-calculate based on current month filter (ignoring sort)
    const currentMonthTx = transactions.filter(t => t.date.startsWith(filterDate));
    const income = currentMonthTx
      .filter(t => t.type === TransactionType.INCOME)
      .reduce((acc, curr) => acc + curr.amount, 0);
    const expense = currentMonthTx
      .filter(t => t.type === TransactionType.EXPENSE)
      .reduce((acc, curr) => acc + curr.amount, 0);
    return { income, expense, net: income - expense };
  }, [transactions, filterDate]);

  // History Summary (Group by month, exclude current filterDate)
  const historySummaries = useMemo(() => {
    const summaries: Record<string, { income: number, expense: number, net: number }> = {};
    transactions.forEach(t => {
      const monthKey = t.date.slice(0, 7); // YYYY-MM
      if (monthKey === filterDate) return; // Exclude current view

      if (!summaries[monthKey]) {
        summaries[monthKey] = { income: 0, expense: 0, net: 0 };
      }
      if (t.type === TransactionType.INCOME) {
        summaries[monthKey].income += t.amount;
        summaries[monthKey].net += t.amount;
      } else {
        summaries[monthKey].expense += t.amount;
        summaries[monthKey].net -= t.amount;
      }
    });
    // Sort descending (Newest months first) and take top 12
    return Object.entries(summaries)
      .sort((a, b) => b[0].localeCompare(a[0]))
      .slice(0, 12);
  }, [transactions, filterDate]);

  const formatDateDisplay = (dateStr: string) => {
    // Convert YYYY-MM-DD to DD/MM/YYYY
    if (!dateStr) return '';
    const parts = dateStr.split('-');
    if (parts.length === 3) {
      return `${parts[2]}/${parts[1]}/${parts[0]}`;
    }
    return dateStr;
  };

  const getBurmeseMonthName = (dateStr: string) => {
    const [year, month] = dateStr.split('-');
    const monthIndex = parseInt(month) - 1;
    const months = [
      "ဇန်နဝါရီ", "ဖေဖော်ဝါရီ", "မတ်", "ဧပြီ", "မေ", "ဇွန်", 
      "ဇူလိုင်", "သြဂုတ်", "စက်တင်ဘာ", "အောက်တိုဘာ", "နိုဝင်ဘာ", "ဒီဇင်ဘာ"
    ];
    return `${year} ${months[monthIndex]}လ`;
  };

  const isCurrentMonth = filterDate === currentMonth;

  if (isLoading && transactions.length === 0) {
    return (
        <div className="min-h-screen bg-dark-bg flex items-center justify-center text-emerald-500">
            <Loader2 className="animate-spin" size={48} />
        </div>
    )
  }

  return (
    <div className="min-h-screen bg-dark-bg pb-24 text-dark-text font-sans">
      {/* Header */}
      <header className="bg-dark-card shadow-md sticky top-0 z-20 border-b border-dark-border">
        <div className="max-w-4xl mx-auto px-4 py-4 flex justify-between items-center">
          <div>
            <h1 className="text-xl font-bold text-white">ငွေစာရင်း</h1>
            <p className="text-xs text-dark-muted">အသုံးပြုသူ: {currentUser}</p>
          </div>
          <div className="flex gap-2">
            <button 
                onClick={handleExportCSV} 
                className="text-dark-muted hover:text-emerald-400 transition text-xs border border-dark-border px-2 py-1 rounded flex items-center gap-1"
                title="CSV ဒေါင်းလုဒ်လုပ်ရန်"
            >
                <Download size={14} /> Export
            </button>
            <button onClick={handleLogout} className="text-dark-muted hover:text-red-500 transition text-xs border border-dark-border px-2 py-1 rounded flex items-center gap-1">
                <LogOut size={14} /> ထွက်မည်
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-6 space-y-6">
        
        {/* Transaction Table */}
        <div className="bg-dark-card rounded-xl shadow-sm border border-dark-border overflow-hidden">
          <div className="p-4 border-b border-dark-border bg-slate-800/50">
            <div className="flex justify-between items-center mb-2">
              <h3 className="font-bold text-gray-200">
                {getBurmeseMonthName(filterDate)} ငွေစာရင်း
              </h3>
              <span className="text-xs text-dark-muted bg-slate-700 px-2 py-1 rounded border border-dark-border">{filteredAndSortedTransactions.length} ခု</span>
            </div>
            
            {/* Monthly Stats Header */}
            <div className="flex gap-4 text-xs sm:text-sm bg-slate-900/50 p-2 rounded-lg justify-around">
               <div className="flex flex-col items-center">
                 <span className="text-dark-muted text-[10px]">ဝင်ငွေ</span>
                 <span className="text-emerald-400 font-bold">+{monthlyStats.income.toLocaleString()} ကျပ်</span>
               </div>
               <div className="w-px bg-dark-border"></div>
               <div className="flex flex-col items-center">
                 <span className="text-dark-muted text-[10px]">ထွက်ငွေ</span>
                 <span className="text-red-400 font-bold">-{monthlyStats.expense.toLocaleString()} ကျပ်</span>
               </div>
               <div className="w-px bg-dark-border"></div>
               <div className="flex flex-col items-center">
                 <span className="text-dark-muted text-[10px]">လလက်ကျန်</span>
                 <span className={`${monthlyStats.net >= 0 ? 'text-emerald-400' : 'text-red-400'} font-bold`}>
                    {monthlyStats.net > 0 ? '+' : ''}{monthlyStats.net.toLocaleString()} ကျပ်
                 </span>
               </div>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-dark-text">
              <thead className="bg-slate-800 text-dark-muted font-medium border-b border-dark-border">
                <tr>
                  <th 
                    onClick={() => handleSort('date')}
                    className="px-4 py-3 cursor-pointer hover:bg-slate-700/50 hover:text-white transition select-none w-1/4"
                  >
                    <div className="flex items-center">ရက်စွဲ {getSortIcon('date')}</div>
                  </th>
                  <th 
                    onClick={() => handleSort('label')}
                    className="px-4 py-3 cursor-pointer hover:bg-slate-700/50 hover:text-white transition select-none w-2/4"
                  >
                    <div className="flex items-center">အကြောင်းအရာ {getSortIcon('label')}</div>
                  </th>
                  <th 
                    onClick={() => handleSort('amount')}
                    className="px-4 py-3 text-right cursor-pointer hover:bg-slate-700/50 hover:text-white transition select-none w-1/4"
                  >
                     <div className="flex items-center justify-end">ပမာဏ {getSortIcon('amount')}</div>
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-dark-border">
                {filteredAndSortedTransactions.length === 0 ? (
                  <tr>
                    <td colSpan={3} className="px-4 py-8 text-center text-dark-muted italic">
                      စာရင်းမရှိသေးပါ
                    </td>
                  </tr>
                ) : (
                  filteredAndSortedTransactions.map((t) => (
                    <tr 
                        key={t.id} 
                        onClick={() => handleRowClick(t)}
                        className="hover:bg-slate-800/50 transition cursor-pointer active:bg-slate-800 group"
                    >
                      <td className="px-4 py-3 whitespace-nowrap text-dark-muted">
                        {formatDateDisplay(t.date)}
                      </td>
                      <td className="px-4 py-3">
                        <div className="font-medium text-white">{t.label}</div>
                      </td>
                      <td className={`px-4 py-3 text-right font-bold ${t.type === TransactionType.INCOME ? 'text-emerald-400' : 'text-red-400'}`}>
                        {t.type === TransactionType.INCOME ? '+' : '-'}{t.amount.toLocaleString()}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Home Button (When viewing history) */}
        {!isCurrentMonth && (
            <button 
                onClick={() => setFilterDate(currentMonth)}
                className="w-full py-3 rounded-xl border border-primary text-primary hover:bg-primary/10 transition flex items-center justify-center gap-2 font-bold"
            >
                <Home size={20} />
                လက်ရှိလသို့ ပြန်သွားမည်
            </button>
        )}

        {/* History List */}
        <div className="space-y-3 pt-4 border-t border-dark-border">
          <h3 className="text-dark-muted text-sm font-bold uppercase tracking-wider">လဟောင်း စာရင်းများ</h3>
          {historySummaries.length === 0 ? (
             <p className="text-dark-muted text-sm">လဟောင်းစာရင်း မရှိသေးပါ</p>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {historySummaries.map(([monthKey, stats]) => (
                <button 
                  key={monthKey}
                  onClick={() => {
                      setFilterDate(monthKey);
                      window.scrollTo({ top: 0, behavior: 'smooth' });
                  }}
                  className="bg-dark-card p-3 rounded-lg border border-dark-border hover:border-primary/50 transition text-left group"
                >
                  <div className="flex justify-between items-center mb-1">
                    <span className="font-bold text-white group-hover:text-primary transition">{getBurmeseMonthName(monthKey)}</span>
                    <span className={`text-xs font-bold ${stats.net >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                      {stats.net > 0 ? '+' : ''}{stats.net.toLocaleString()}
                    </span>
                  </div>
                  <div className="flex justify-between text-xs text-dark-muted">
                    <span>ဝင်: {stats.income.toLocaleString()}</span>
                    <span>ထွက်: {stats.expense.toLocaleString()}</span>
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>
      </main>

      {/* Floating Action Button */}
      {isCurrentMonth && (
        <button
          onClick={() => {
              resetForm();
              setShowForm(true);
          }}
          className="fixed bottom-6 right-6 bg-primary hover:bg-emerald-600 text-slate-900 rounded-full p-4 shadow-lg shadow-emerald-900/20 transition hover:scale-105 active:scale-95 z-30"
          aria-label="Add Transaction"
        >
          <Plus size={28} strokeWidth={2.5} />
        </button>
      )}

      {/* Input Modal / Bottom Sheet - UPDATED FOR KEYBOARD VISIBILITY */}
      {showForm && (
        <div className="fixed inset-0 bg-black/80 z-40 flex items-center justify-center p-4">
          <div className="bg-slate-800 w-full max-w-lg rounded-2xl p-6 shadow-2xl animate-in zoom-in-95 duration-200 border border-slate-700 max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-xl font-bold text-white">
                {editingId ? 'စာရင်း ပြင်ဆင်ရန်' : 'စာရင်းသစ် ထည့်ရန်'}
              </h2>
              <button 
                onClick={resetForm}
                className="text-dark-muted hover:text-white transition"
              >
                <X size={24} />
              </button>
            </div>

            <form onSubmit={handleSaveTransaction} className="space-y-5">
              
              {/* Type Selector */}
              <div className="grid grid-cols-2 gap-3 p-1 bg-slate-900 rounded-xl">
                <button
                  type="button"
                  onClick={() => setType(TransactionType.EXPENSE)}
                  className={`py-2.5 rounded-lg text-sm font-bold transition flex items-center justify-center gap-2 ${
                    type === TransactionType.EXPENSE
                      ? 'bg-red-500 text-white shadow-lg'
                      : 'text-dark-muted hover:text-white'
                  }`}
                >
                  <ArrowDown size={16} /> ထွက်ငွေ
                </button>
                <button
                  type="button"
                  onClick={() => setType(TransactionType.INCOME)}
                  className={`py-2.5 rounded-lg text-sm font-bold transition flex items-center justify-center gap-2 ${
                    type === TransactionType.INCOME
                      ? 'bg-emerald-500 text-slate-900 shadow-lg'
                      : 'text-dark-muted hover:text-white'
                  }`}
                >
                  <ArrowUp size={16} /> ဝင်ငွေ
                </button>
              </div>

              <div>
                <label className="block text-dark-muted text-xs font-bold mb-1.5 uppercase tracking-wider">
                  ပမာဏ (ကျပ်)
                </label>
                <input
                  type="number"
                  inputMode="numeric"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  className="w-full bg-slate-700 text-white text-2xl font-bold px-4 py-3 rounded-xl border-2 border-transparent focus:border-primary focus:outline-none transition placeholder-slate-500"
                  placeholder="0"
                  autoFocus
                />
              </div>

              <div>
                <label className="block text-dark-muted text-xs font-bold mb-1.5 uppercase tracking-wider">
                  အကြောင်းအရာ
                </label>
                <input
                  type="text"
                  value={label}
                  onChange={(e) => setLabel(e.target.value)}
                  className="w-full bg-slate-700 text-white px-4 py-3 rounded-xl border-2 border-transparent focus:border-primary focus:outline-none transition placeholder-slate-500"
                  placeholder="ဥပမာ - မနက်စာ"
                />
              </div>

              <button
                type="submit"
                disabled={isSaving || !amount || !label}
                className="w-full bg-primary hover:bg-emerald-600 text-slate-900 font-bold py-4 rounded-xl shadow-lg shadow-emerald-900/20 transition disabled:opacity-50 disabled:cursor-not-allowed flex justify-center items-center gap-2 mt-4"
              >
                {isSaving ? (
                    <Loader2 className="animate-spin" /> 
                ) : (
                    <>
                        {editingId ? <Save size={20} /> : <Plus size={20} />}
                        {editingId ? 'သိမ်းဆည်းမည်' : 'စာရင်းသွင်းမည်'}
                    </>
                )}
              </button>
            </form>
          </div>
        </div>
      )}

      {/* Action Modal (When clicking a row) */}
      {selectedTransaction && (
        <div 
          className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center p-4 backdrop-blur-sm"
          onClick={() => setSelectedTransaction(null)}
        >
          <div 
            className="bg-slate-800 rounded-2xl w-full max-w-sm p-6 space-y-6 shadow-2xl border border-slate-700 animate-in zoom-in-95 duration-200"
            onClick={e => e.stopPropagation()}
          >
            <div className="flex justify-between items-start">
              <div>
                 <h3 className="text-lg font-bold text-white break-words">{selectedTransaction.label}</h3>
                 <p className="text-dark-muted text-sm">{formatDateDisplay(selectedTransaction.date)}</p>
              </div>
              <button onClick={() => setSelectedTransaction(null)} className="text-dark-muted hover:text-white bg-slate-700 p-1 rounded-full">
                <X size={20} />
              </button>
            </div>
            
            <div className="text-3xl font-bold text-center py-2 bg-slate-900/50 rounded-xl">
              <span className={selectedTransaction.type === TransactionType.INCOME ? 'text-emerald-400' : 'text-red-400'}>
                {selectedTransaction.type === TransactionType.INCOME ? '+' : '-'}{selectedTransaction.amount.toLocaleString()} <span className="text-sm text-dark-muted font-normal">ကျပ်</span>
              </span>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <button 
                onClick={handleEditClick}
                className="flex flex-col items-center justify-center gap-2 bg-slate-700 hover:bg-blue-600/20 hover:border-blue-500/50 border border-transparent p-4 rounded-xl transition group"
              >
                <div className="bg-blue-500/10 p-3 rounded-full group-hover:bg-blue-500 text-blue-400 group-hover:text-white transition">
                  <Edit size={24} />
                </div>
                <span className="text-sm font-bold text-blue-100 group-hover:text-blue-400">ပြင်ဆင်မည်</span>
              </button>
              
              <button 
                onClick={handleDeleteClick}
                className="flex flex-col items-center justify-center gap-2 bg-slate-700 hover:bg-red-600/20 hover:border-red-500/50 border border-transparent p-4 rounded-xl transition group"
              >
                 <div className="bg-red-500/10 p-3 rounded-full group-hover:bg-red-500 text-red-400 group-hover:text-white transition">
                  <Trash2 size={24} />
                </div>
                <span className="text-sm font-bold text-red-100 group-hover:text-red-400">ဖျက်မည်</span>
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default Dashboard;